### ISSUE TITLE
How to build node.js based web app using this Action ?

### ISSUE THREAD

**Issue by absurdfounder** [lowply/deploy-firebase#12]
Hello , i need to build an app with node.js, your existing action seems to work great for static files/repositories .
But i am not sure how it works with files that require node installed and setup.

**Comment by abraham** [comment]
You can use the setup-node action and build before deploying.

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: name-of-project
```
